geodjango/urls.py
from django.conf.urls import include, url
from django.contrib.gis import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^world/', include('world.urls', namespace="world")),
]

world/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='Index'),
    url(r'^states/$', views.states, name='States'),
    url(r'^api/testpoints$', views.updateGeoLocation, name='updateGeoLocation'),
]

world/models.py
from django.contrib.gis.db import models


class WorldBorder(models.Model):
    # Regular Django fields corresponding to the attributes in the
    # world borders shapefile
    name = models.CharField(max_length=50)
    area = models.IntegerField()
    pop2005 = models.IntegerField('Population 2005')
    fips = models.CharField('FIPS Code', max_length=2)
    iso2 = models.CharField('2 DIGIT ISO', max_length=2)
    iso3 = models.CharField('3 DIGIT ISO', max_length=3)
    un = models.IntegerField('UN Code')
    region = models.IntegerField('Region code')
    subregion = models.IntegerField('Sub-region code')
    lon = models.FloatField('Longitude')
    lat = models.FloatField('Longitude')

    # GeoDjango specific: a geometry field (MultiPolygonField), and
    # overriding the default manager with a GeoManager instance.
    mpoly = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __str__(self):
        return self.name


class StatesBorder(models.Model):
    name = models.CharField(max_length=25)
    state_fips = models.CharField(max_length=2)
    sub_region = models.CharField(max_length=20)
    state_abbr = models.CharField(max_length=2)
    pop2010 = models.IntegerField()
    pop2012 = models.IntegerField()
    sqmi = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return self.name


class USCities(models.Model):
    name = models.CharField(max_length=40)
    class_id = models.CharField(max_length=30)
    st = models.CharField(max_length=2)
    stfips = models.CharField(max_length=2)
    arealand = models.FloatField()
    areawater = models.FloatField()
    pop2000 = models.IntegerField()
    pop2007 = models.IntegerField()
    geom = models.PointField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return self.name


class Rivers(models.Model):
    scalerank = models.IntegerField()
    featurecla = models.CharField(max_length=32)
    name = models.CharField(max_length=254)
    name_alt = models.CharField(max_length=254)
    geom = models.LineStringField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return self.name


class TestPoints(models.Model):
    name = models.CharField(max_length=50)
    popularity = models.IntegerField()
    geom = models.PointField(srid=4326)
    objects = models.GeoManager()

    def __str__(self):
        return self.name

world/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import WorldBorder, StatesBorder, TestPoints
from .customsql import getGeoJSON, getGJ
import json
from django.contrib.gis.geos import Point
# import json


def index(request):
    # my_tab = "'public.world_statesborder'"
    # params = "'id, name, pop2012'"
    states = getGeoJSON()
    rivers = getGJ('public.world_rivers', 'name, featurecla')
    cities = getGJ('public.world_uscities', 'name, pop2007')

    return render(request, 'world/index.html', {'states': states,
        'rivers': rivers, 'cities': cities})


def states(request):
    qs = StatesBorder.objects.all().geojson()
    return render(request, 'world/index.html', {'borders': qs})


def updateGeoLocation(request):
    if request.method == 'POST':
        body = json.loads(request.body)
        if 'geoLocation' in body:
            geoLocation = body['geoLocation']
            # update table with this new geoLocation
            point = TestPoints(name="test", popularity=0, geom=Point(geoLocation[0], geoLocation[1]))
            point.save()
            return JsonResponse({'id': point.id})

    return HttpResponse('Oops. Something went wrong updating geoLocation', status=500)

world/templates/base/base.html
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>{% block title_html %} {%endblock%}</title>
        {% load staticfiles %}
            <link href="{% static "css/ol.css" %}" rel="stylesheet" type="text/css"/>
            <link href="{% static "css/mapStyles.css" %}" rel="stylesheet" type="text/css"/>
            <script src="{% static "js/lib/ol-debug.js" %}"></script>
            <script src="{% static "js/lib/jquery-debug.js" %}"></script>
        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        {% block body_content %} {% endblock %}           
    </body>
</html>

world/templates/world/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title_html %}
    Mapping attempt by Nate
{% endblock %}
{% block extrahead %}
    {% comment %}<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script src="http://d3js.org/topojson.v1.min.js"></script>{% endcomment %}
{% endblock %}
{% block body_content %}

    <div id="map" class="map"></div>
	{% comment %} <script src="{% static "js/mapping.js" %}"></script> {% endcomment %}

	<script type="text/javascript">

		function init () {

			var stamen_layer = new ol.layer.Tile({
		        source: new ol.source.Stamen({
		            layer: 'watercolor'
		        })
		    });

		    //var center_point = ol.proj.transform([-97.95, 29.89], 'EPSG:4326', 'EPSG:3857'); // centered on San Marcos, Texas
		    var center_point = ol.proj.transform([0, 0], 'EPSG:4326', 'EPSG:3857'); // centered at 0 long, 0 lat

		    var view = new ol.View({
		        center: center_point,
		        zoom: 2
		    });

		    var map = new ol.Map({
		        target: 'map',
		    });

		/*
		    var worldVector = new ol.layer.Vector({
		        source: new ol.source.Vector({
		            url: '{% static "geo/world2_nc.json" %}',
		            projection: 'EPSG:4326',
		            format: new ol.format.GeoJSON()
		        })
		    });
		*/

        var states = {{ states | safe }};
        if (!states.features) states.features = [];
		    var gjformat = new ol.format.GeoJSON();
		    var feat = gjformat.readFeatures(states, {
		        dataProjection: 'EPSG:4326',
		        featureProjection: 'EPSG:3857'
		        }
		    );
		    var sourceVector = new ol.source.Vector({
		        features: feat
		    });

		    var statesVector = new ol.layer.Vector({
		        source: sourceVector,
		        projection: 'EPSG:4326'
		    });

        var rivers = {{ rivers | safe }};
        if (!rivers.features) rivers.features = [];
		    var riverVector = new ol.layer.Vector({
		        source: new ol.source.Vector({
		            features: (new ol.format.GeoJSON()).readFeatures(rivers,{
		                dataProjection: 'EPSG:4326',
		                featureProjection: 'EPSG:3857'
		            })
		        })
		    });

        var cities = {{ cities | safe }};
        if (!cities.features) cities.features = [];
		    var citiesVector = new ol.layer.Vector({
		        source: new ol.source.Vector({
		            features: (new ol.format.GeoJSON()).readFeatures(cities,{
		                dataProjection: 'EPSG:4326',
		                featureProjection: 'EPSG:3857'
		            })
		        })
		    });

		    var geoLocation = new ol.Geolocation({
		        projection: view.getProjection(), // projection EPSG:3857 (web mercator)...projection coordinate will be in
		        tracking: true
		    });

		    //var positionFeature = new ol.Feature(new ol.geom.Point([0, 0]));
		    //positionFeature.getGeometry().transform('EPSG:4326', 'EPSG:3857')
		    var positionFeature = new ol.Feature();
		    positionFeature.setStyle(new ol.style.Style({
		        image: new ol.style.Circle({
		            radius: 6,
		            fill: new ol.style.Fill({
		                //color: '#3399CC'
		                color: '#F9E436'
		            }),
		            stroke: new ol.style.Stroke({
		                color: '#FFC000',
		                width: 2
		            })
		        })
		    }));

		    var positionVector = new ol.layer.Vector({
		        source: new ol.source.Vector({
		            features: [positionFeature]
		        })
		    });

		    var trackPositions = new ol.geom.LineString([], 'XY');
		    var trackFeature = new ol.Feature(trackPositions);
		    var trackVector = new ol.layer.Vector({
		        source: new ol.source.Vector({
		            features: [trackFeature]
		        })
		    });

		    geoLocation.on('change:position', function() {
		        var coordinates = geoLocation.getPosition();
		        //window.alert("Position changed to: " + coordinates);
		        positionFeature.setGeometry(coordinates ? new ol.geom.Point(coordinates): null);
		        trackPositions.appendCoordinate(coordinates);


		        // Add code to pass location to PostGIS DB
		        // which will then fire an event trigger
		        // and inform all users of the app of the
		        // change in location.
		        // (Will need to use Python Twisted?)
            $.ajax({
              type: "POST",
              url: "{% url 'world:updateGeoLocation' %}",
              data: JSON.stringify({ "geoLocation": coordinates }),
              dataType: "json",
              contentType: "application/json",
              success: function(){
                console.log("test point added");
                console.log(arguments);
              },
              error: function(err){
                console.log(err);
              }
            });

		    });

		    map.addLayer(stamen_layer);
		    //map.addLayer(worldVector);
		    map.addLayer(statesVector);
		    map.addLayer(riverVector);
		    //map.addLayer(citiesVector);
		    map.addLayer(positionVector);
		    map.addLayer(trackVector);
		    map.setView(view);
		}

		$(document).ready(function() {
      function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
              }
          }
      });
			init();
		});

	</script>

{% endblock %}

world/templates/world/index1.html
<!DOCTYPE html>
<html>
<head>
<title>GeoJSON example</title>
<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.6.0/ol.css" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.6.0/ol.js"></script>

</head>
<body>
<div class="container-fluid">

<div class="row-fluid">
  <div class="span12">
    <div id="map" class="map"></div>
  </div>
</div>

</div>
<script>
var image = new ol.style.Circle({
  radius: 5,
  fill: null,
  stroke: new ol.style.Stroke({color: 'red', width: 1})
});

var styles = {
  'Point': [new ol.style.Style({
    image: image
  })],
  'LineString': [new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'green',
      width: 1
    })
  })],
  'MultiLineString': [new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'green',
      width: 1
    })
  })],
  'MultiPoint': [new ol.style.Style({
    image: image
  })],
  'MultiPolygon': [new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'yellow',
      width: 1
    }),
    fill: new ol.style.Fill({
      color: 'rgba(255, 255, 0, 0.1)'
    })
  })],
  'Polygon': [new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'blue',
      lineDash: [4],
      width: 3
    }),
    fill: new ol.style.Fill({
      color: 'rgba(0, 0, 255, 0.1)'
    })
  })],
  'GeometryCollection': [new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'magenta',
      width: 2
    }),
    fill: new ol.style.Fill({
      color: 'magenta'
    }),
    image: new ol.style.Circle({
      radius: 10,
      fill: null,
      stroke: new ol.style.Stroke({
        color: 'magenta'
      })
    })
  })],
  'Circle': [new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'red',
      width: 2
    }),
    fill: new ol.style.Fill({
      color: 'rgba(255,0,0,0.2)'
    })
  })]
};

var styleFunction = function(feature, resolution) {
  return styles[feature.getGeometry().getType()];
};

var geojsonObject = {
  'type': 'FeatureCollection',
  'crs': {
    'type': 'name',
    'properties': {
      'name': 'EPSG:3857'
    }
  },
  'features': [
    {
      'type': 'Feature',
      'geometry': {
        'type': 'Point',
        'coordinates': [0, 0]
      }
    },
    {
      'type': 'Feature',
      'geometry': {
        'type': 'LineString',
        'coordinates': [[4e6, -2e6], [8e6, 2e6]]
      }
    },
    {
      'type': 'Feature',
      'geometry': {
        'type': 'LineString',
        'coordinates': [[4e6, 2e6], [8e6, -2e6]]
      }
    },
    {
      'type': 'Feature',
      'geometry': {
        'type': 'Polygon',
        'coordinates': [[[-5e6, -1e6], [-4e6, 1e6], [-3e6, -1e6]]]
      }
    },
    {
      'type': 'Feature',
      'geometry': {
        'type': 'MultiLineString',
        'coordinates': [
          [[-1e6, -7.5e5], [-1e6, 7.5e5]],
          [[1e6, -7.5e5], [1e6, 7.5e5]],
          [[-7.5e5, -1e6], [7.5e5, -1e6]],
          [[-7.5e5, 1e6], [7.5e5, 1e6]]
        ]
      }
    },
    {
      'type': 'Feature',
      'geometry': {
        'type': 'MultiPolygon',
        'coordinates': [
          [[[-5e6, 6e6], [-5e6, 8e6], [-3e6, 8e6], [-3e6, 6e6]]],
          [[[-2e6, 6e6], [-2e6, 8e6], [0, 8e6], [0, 6e6]]],
          [[[1e6, 6e6], [1e6, 8e6], [3e6, 8e6], [3e6, 6e6]]]
        ]
      }
    },
    {
      'type': 'Feature',
      'geometry': {
        'type': 'GeometryCollection',
        'geometries': [
          {
            'type': 'LineString',
            'coordinates': [[-5e6, -5e6], [0, -5e6]]
          },
          {
            'type': 'Point',
            'coordinates': [4e6, -5e6]
          },
          {
            'type': 'Polygon',
            'coordinates': [[[1e6, -6e6], [2e6, -4e6], [3e6, -6e6]]]
          }
        ]
      }
    }
  ]
};
window.alert(typeof(geojsonObject));

var vectorSource = new ol.source.Vector({
  features: (new ol.format.GeoJSON()).readFeatures(geojsonObject)
});

//vectorSource.addFeature(new ol.Feature(new ol.geom.Circle([5e6, 7e6], 1e6)));

var vectorLayer = new ol.layer.Vector({
  source: vectorSource,
  style: styleFunction
});

var map = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM()
    }),
    vectorLayer
  ],
  target: 'map',
  controls: ol.control.defaults({
    attributionOptions: /** @type {olx.control.AttributionOptions} */ ({
      collapsible: false
    })
  }),
  view: new ol.View({
    center: [0, 0],
    zoom: 2
  })
});

</script>
</body>
</html>